# coding: utf-8

"""
    Halu API

    This should be a basic guide for the new Halu API. It will be updated as soon as I add new messages (or i'll try). The IP address to communicate with the master lamp is 10.0.0.1 by default.

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into sdk package
from .models.access_point import AccessPoint
from .models.action import Action
from .models.action_response import ActionResponse
from .models.add_response import AddResponse
from .models.added_id import AddedId
from .models.ambiance import Ambiance
from .models.ambiance_id import AmbianceId
from .models.ambiance_response import AmbianceResponse
from .models.client import Client
from .models.color import Color
from .models.components import Components
from .models.connect import Connect
from .models.database import Database
from .models.database_response import DatabaseResponse
from .models.discovery import Discovery
from .models.effect import Effect
from .models.group import Group
from .models.group_response import GroupResponse
from .models.lamp import Lamp
from .models.lamp_response import LampResponse
from .models.lamp_settings import LampSettings
from .models.ota_file import OtaFile
from .models.ota_status import OtaStatus
from .models.position import Position
from .models.scheduled import Scheduled
from .models.scheduled_response import ScheduledResponse
from .models.scheduling import Scheduling
from .models.sequence import Sequence
from .models.sequence_response import SequenceResponse
from .models.space import Space
from .models.space_response import SpaceResponse
from .models.ssid import Ssid
from .models.step import Step
from .models.target import Target
from .models.wizard import Wizard
from .models.wizard_data import WizardData
from .models.wizard_response import WizardResponse

# import apis into sdk package
from .apis.action_api import ActionApi
from .apis.ambiance_api import AmbianceApi
from .apis.broadcast_api import BroadcastApi
from .apis.connect_api import ConnectApi
from .apis.database_api import DatabaseApi
from .apis.discovery_api import DiscoveryApi
from .apis.effect_api import EffectApi
from .apis.group_api import GroupApi
from .apis.lamp_api import LampApi
from .apis.lamp_settings_api import LampSettingsApi
from .apis.notification_api import NotificationApi
from .apis.ota_file_api import OtaFileApi
from .apis.ota_status_api import OtaStatusApi
from .apis.scheduled_api import ScheduledApi
from .apis.sequence_api import SequenceApi
from .apis.space_api import SpaceApi
from .apis.ssid_api import SsidApi
from .apis.wizard_api import WizardApi

# import ApiClient
from .api_client import ApiClient

from .configuration import Configuration

configuration = Configuration()
