# coding: utf-8

"""
    Halu API

    This should be a basic guide for the new Halu API. It will be updated as soon as I add new messages (or i'll try). The IP address to communicate with the master lamp is 10.0.0.1 by default.

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Ambiance(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id=None, icon=None, name=None, actions=None, scheduling=None):
        """
        Ambiance - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'id': 'int',
            'icon': 'int',
            'name': 'str',
            'actions': 'list[Action]',
            'scheduling': 'list[Scheduling]'
        }

        self.attribute_map = {
            'id': 'id',
            'icon': 'icon',
            'name': 'name',
            'actions': 'actions',
            'scheduling': 'scheduling'
        }

        self._id = id
        self._icon = icon
        self._name = name
        self._actions = actions
        self._scheduling = scheduling

    @property
    def id(self):
        """
        Gets the id of this Ambiance.

        :return: The id of this Ambiance.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this Ambiance.

        :param id: The id of this Ambiance.
        :type: int
        """

        self._id = id

    @property
    def icon(self):
        """
        Gets the icon of this Ambiance.

        :return: The icon of this Ambiance.
        :rtype: int
        """
        return self._icon

    @icon.setter
    def icon(self, icon):
        """
        Sets the icon of this Ambiance.

        :param icon: The icon of this Ambiance.
        :type: int
        """

        self._icon = icon

    @property
    def name(self):
        """
        Gets the name of this Ambiance.

        :return: The name of this Ambiance.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this Ambiance.

        :param name: The name of this Ambiance.
        :type: str
        """

        self._name = name

    @property
    def actions(self):
        """
        Gets the actions of this Ambiance.

        :return: The actions of this Ambiance.
        :rtype: list[Action]
        """
        return self._actions

    @actions.setter
    def actions(self, actions):
        """
        Sets the actions of this Ambiance.

        :param actions: The actions of this Ambiance.
        :type: list[Action]
        """

        self._actions = actions

    @property
    def scheduling(self):
        """
        Gets the scheduling of this Ambiance.

        :return: The scheduling of this Ambiance.
        :rtype: list[Scheduling]
        """
        return self._scheduling

    @scheduling.setter
    def scheduling(self, scheduling):
        """
        Sets the scheduling of this Ambiance.

        :param scheduling: The scheduling of this Ambiance.
        :type: list[Scheduling]
        """

        self._scheduling = scheduling

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Ambiance):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
