# coding: utf-8

"""
    Halu API

    This should be a basic guide for the new Halu API. It will be updated as soon as I add new messages (or i'll try). The IP address to communicate with the master lamp is 10.0.0.1 by default.

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Color(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, fade=None, intensity=None, components=None):
        """
        Color - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'fade': 'float',
            'intensity': 'float',
            'components': 'Components'
        }

        self.attribute_map = {
            'fade': 'fade',
            'intensity': 'intensity',
            'components': 'components'
        }

        self._fade = fade
        self._intensity = intensity
        self._components = components

    @property
    def fade(self):
        """
        Gets the fade of this Color.

        :return: The fade of this Color.
        :rtype: float
        """
        return self._fade

    @fade.setter
    def fade(self, fade):
        """
        Sets the fade of this Color.

        :param fade: The fade of this Color.
        :type: float
        """

        self._fade = fade

    @property
    def intensity(self):
        """
        Gets the intensity of this Color.

        :return: The intensity of this Color.
        :rtype: float
        """
        return self._intensity

    @intensity.setter
    def intensity(self, intensity):
        """
        Sets the intensity of this Color.

        :param intensity: The intensity of this Color.
        :type: float
        """

        self._intensity = intensity

    @property
    def components(self):
        """
        Gets the components of this Color.

        :return: The components of this Color.
        :rtype: Components
        """
        return self._components

    @components.setter
    def components(self, components):
        """
        Sets the components of this Color.

        :param components: The components of this Color.
        :type: Components
        """

        self._components = components

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Color):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
