# coding: utf-8

"""
    Halu API

    This should be a basic guide for the new Halu API. It will be updated as soon as I add new messages (or i'll try). The IP address to communicate with the master lamp is 10.0.0.1 by default.

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Effect(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, duration=None, cyclic=None, priority=None, steps=None):
        """
        Effect - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'duration': 'int',
            'cyclic': 'bool',
            'priority': 'int',
            'steps': 'list[Step]'
        }

        self.attribute_map = {
            'duration': 'duration',
            'cyclic': 'cyclic',
            'priority': 'priority',
            'steps': 'steps'
        }

        self._duration = duration
        self._cyclic = cyclic
        self._priority = priority
        self._steps = steps

    @property
    def duration(self):
        """
        Gets the duration of this Effect.

        :return: The duration of this Effect.
        :rtype: int
        """
        return self._duration

    @duration.setter
    def duration(self, duration):
        """
        Sets the duration of this Effect.

        :param duration: The duration of this Effect.
        :type: int
        """

        self._duration = duration

    @property
    def cyclic(self):
        """
        Gets the cyclic of this Effect.

        :return: The cyclic of this Effect.
        :rtype: bool
        """
        return self._cyclic

    @cyclic.setter
    def cyclic(self, cyclic):
        """
        Sets the cyclic of this Effect.

        :param cyclic: The cyclic of this Effect.
        :type: bool
        """

        self._cyclic = cyclic

    @property
    def priority(self):
        """
        Gets the priority of this Effect.

        :return: The priority of this Effect.
        :rtype: int
        """
        return self._priority

    @priority.setter
    def priority(self, priority):
        """
        Sets the priority of this Effect.

        :param priority: The priority of this Effect.
        :type: int
        """

        self._priority = priority

    @property
    def steps(self):
        """
        Gets the steps of this Effect.

        :return: The steps of this Effect.
        :rtype: list[Step]
        """
        return self._steps

    @steps.setter
    def steps(self, steps):
        """
        Sets the steps of this Effect.

        :param steps: The steps of this Effect.
        :type: list[Step]
        """

        self._steps = steps

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Effect):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
