# coding: utf-8

"""
    Halu API

    This should be a basic guide for the new Halu API. It will be updated as soon as I add new messages (or i'll try). The IP address to communicate with the master lamp is 10.0.0.1 by default.

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Wizard(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, access_point=None, client=None, lamps=None):
        """
        Wizard - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'access_point': 'AccessPoint',
            'client': 'Client',
            'lamps': 'list[str]'
        }

        self.attribute_map = {
            'access_point': 'access_point',
            'client': 'client',
            'lamps': 'lamps'
        }

        self._access_point = access_point
        self._client = client
        self._lamps = lamps

    @property
    def access_point(self):
        """
        Gets the access_point of this Wizard.

        :return: The access_point of this Wizard.
        :rtype: AccessPoint
        """
        return self._access_point

    @access_point.setter
    def access_point(self, access_point):
        """
        Sets the access_point of this Wizard.

        :param access_point: The access_point of this Wizard.
        :type: AccessPoint
        """

        self._access_point = access_point

    @property
    def client(self):
        """
        Gets the client of this Wizard.

        :return: The client of this Wizard.
        :rtype: Client
        """
        return self._client

    @client.setter
    def client(self, client):
        """
        Sets the client of this Wizard.

        :param client: The client of this Wizard.
        :type: Client
        """

        self._client = client

    @property
    def lamps(self):
        """
        Gets the lamps of this Wizard.

        :return: The lamps of this Wizard.
        :rtype: list[str]
        """
        return self._lamps

    @lamps.setter
    def lamps(self, lamps):
        """
        Sets the lamps of this Wizard.

        :param lamps: The lamps of this Wizard.
        :type: list[str]
        """

        self._lamps = lamps

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Wizard):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
