# coding: utf-8

"""
    Halu API

    This should be a basic guide for the new Halu API. It will be updated as soon as I add new messages (or i'll try). The IP address to communicate with the master lamp is 10.0.0.1 by default.

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class WizardData(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, converted_lamps=None, state=None, total_lamps=None):
        """
        WizardData - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'converted_lamps': 'int',
            'state': 'str',
            'total_lamps': 'int'
        }

        self.attribute_map = {
            'converted_lamps': 'converted_lamps',
            'state': 'state',
            'total_lamps': 'total_lamps'
        }

        self._converted_lamps = converted_lamps
        self._state = state
        self._total_lamps = total_lamps

    @property
    def converted_lamps(self):
        """
        Gets the converted_lamps of this WizardData.

        :return: The converted_lamps of this WizardData.
        :rtype: int
        """
        return self._converted_lamps

    @converted_lamps.setter
    def converted_lamps(self, converted_lamps):
        """
        Sets the converted_lamps of this WizardData.

        :param converted_lamps: The converted_lamps of this WizardData.
        :type: int
        """

        self._converted_lamps = converted_lamps

    @property
    def state(self):
        """
        Gets the state of this WizardData.

        :return: The state of this WizardData.
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """
        Sets the state of this WizardData.

        :param state: The state of this WizardData.
        :type: str
        """

        self._state = state

    @property
    def total_lamps(self):
        """
        Gets the total_lamps of this WizardData.

        :return: The total_lamps of this WizardData.
        :rtype: int
        """
        return self._total_lamps

    @total_lamps.setter
    def total_lamps(self, total_lamps):
        """
        Sets the total_lamps of this WizardData.

        :param total_lamps: The total_lamps of this WizardData.
        :type: int
        """

        self._total_lamps = total_lamps

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, WizardData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
