# coding: utf-8

"""
    Halu API

    This should be a basic guide for the new Halu API. It will be updated as soon as I add new messages (or i'll try). The IP address to communicate with the master lamp is 10.0.0.1 by default.

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.ota_status_api import OtaStatusApi


class TestOtaStatusApi(unittest.TestCase):
    """ OtaStatusApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.ota_status_api.OtaStatusApi()

    def tearDown(self):
        pass

    def test_get_ota_status(self):
        """
        Test case for get_ota_status

        Retrieves the OTA Status from each lamp.
        """
        pass

    def test_modify_ota_status(self):
        """
        Test case for modify_ota_status

        Makes all the lamps try to connect to the OTA server to update their status.
        """
        pass


if __name__ == '__main__':
    unittest.main()
