# coding: utf-8

"""
    Halu API

    This should be a basic guide for the new Halu API. It will be updated as soon as I add new messages (or i'll try). The IP address to communicate with the master lamp is 10.0.0.1 by default.

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.scheduled_api import ScheduledApi


class TestScheduledApi(unittest.TestCase):
    """ ScheduledApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.scheduled_api.ScheduledApi()

    def tearDown(self):
        pass

    def test_add_scheduled(self):
        """
        Test case for add_scheduled

        Adds  a new Scheduled.
        """
        pass

    def test_delete_scheduled(self):
        """
        Test case for delete_scheduled

        Deletes a scheduled
        """
        pass

    def test_get_scheduled(self):
        """
        Test case for get_scheduled

        Gets information scheduled from its id
        """
        pass

    def test_get_scheduleds(self):
        """
        Test case for get_scheduleds

        Gets all the scheduled information
        """
        pass

    def test_modify_scheduled(self):
        """
        Test case for modify_scheduled

        Modifies an existing scheduled.
        """
        pass


if __name__ == '__main__':
    unittest.main()
