# coding: utf-8

"""
    Halu API

    This should be a basic guide for the new Halu API. It will be updated as soon as I add new messages (or i'll try). The IP address to communicate with the master lamp is 10.0.0.1 by default.

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.group_api import GroupApi


class TestGroupApi(unittest.TestCase):
    """ GroupApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.group_api.GroupApi()

    def tearDown(self):
        pass

    def test_add_group(self):
        """
        Test case for add_group

        Adds a new group.
        """
        pass

    def test_delete_group(self):
        """
        Test case for delete_group

        Deletes a group
        """
        pass

    def test_get_group(self):
        """
        Test case for get_group

        Gets information groups from its id
        """
        pass

    def test_get_groups(self):
        """
        Test case for get_groups

        Gets all the groups information
        """
        pass

    def test_modify_group(self):
        """
        Test case for modify_group

        Modifies an existing group.
        """
        pass

    def test_turn_off_group(self):
        """
        Test case for turn_off_group

        Plays turnOff on a group
        """
        pass

    def test_turn_on_group(self):
        """
        Test case for turn_on_group

        Plays turnOn on a group
        """
        pass


if __name__ == '__main__':
    unittest.main()
