# coding: utf-8

"""
    Halu API

    This should be a basic guide for the new Halu API. It will be updated as soon as I add new messages (or i'll try). The IP address to communicate with the master lamp is 10.0.0.1 by default.

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.ota_file_api import OtaFileApi


class TestOtaFileApi(unittest.TestCase):
    """ OtaFileApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.ota_file_api.OtaFileApi()

    def tearDown(self):
        pass

    def test_adds_ota_file(self):
        """
        Test case for adds_ota_file

        Installs the new upgrade. Once the lamp receives this message, it will install the Upgrade and then reboot.
        """
        pass

    def test_modify_ota_file(self):
        """
        Test case for modify_ota_file

        Starts the download of the OTA image.
        """
        pass


if __name__ == '__main__':
    unittest.main()
