# coding: utf-8

"""
    Halu API

    This should be a basic guide for the new Halu API. It will be updated as soon as I add new messages (or i'll try). The IP address to communicate with the master lamp is 10.0.0.1 by default.

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.lamp_api import LampApi


class TestLampApi(unittest.TestCase):
    """ LampApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.lamp_api.LampApi()

    def tearDown(self):
        pass

    def test_delete_lamp(self):
        """
        Test case for delete_lamp

        Removes a lamp from the network database.
        """
        pass

    def test_get_lamp(self):
        """
        Test case for get_lamp

        Gets information lamp from its id
        """
        pass

    def test_get_lamps(self):
        """
        Test case for get_lamps

        Gets all the lamps information
        """
        pass

    def test_modify_color(self):
        """
        Test case for modify_color

        Plays color
        """
        pass

    def test_turn_off(self):
        """
        Test case for turn_off

        Plays turnOff
        """
        pass

    def test_turn_on(self):
        """
        Test case for turn_on

        Plays turnOn
        """
        pass


if __name__ == '__main__':
    unittest.main()
