# coding: utf-8

"""
    Halu API

    This should be a basic guide for the new Halu API. It will be updated as soon as I add new messages (or i'll try). The IP address to communicate with the master lamp is 10.0.0.1 by default.

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.space_api import SpaceApi


class TestSpaceApi(unittest.TestCase):
    """ SpaceApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.space_api.SpaceApi()

    def tearDown(self):
        pass

    def test_add_space(self):
        """
        Test case for add_space

        Adds  a new Space.
        """
        pass

    def test_delete_space(self):
        """
        Test case for delete_space

        Deletes a space
        """
        pass

    def test_get_space(self):
        """
        Test case for get_space

        Gets all the spaces information
        """
        pass

    def test_get_space_id(self):
        """
        Test case for get_space_id

        Gets information space from its id
        """
        pass

    def test_modify_color_space(self):
        """
        Test case for modify_color_space

        Plays color
        """
        pass

    def test_modify_space(self):
        """
        Test case for modify_space

        Modifies an existing space.
        """
        pass

    def test_turn_off_space(self):
        """
        Test case for turn_off_space

        Plays turnOff
        """
        pass

    def test_turn_on_space(self):
        """
        Test case for turn_on_space

        Plays turnOn
        """
        pass


if __name__ == '__main__':
    unittest.main()
