# coding: utf-8

"""
    Halu API

    This should be a basic guide for the new Halu API. It will be updated as soon as I add new messages (or i'll try). The IP address to communicate with the master lamp is 10.0.0.1 by default.

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.ambiance_api import AmbianceApi


class TestAmbianceApi(unittest.TestCase):
    """ AmbianceApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.ambiance_api.AmbianceApi()

    def tearDown(self):
        pass

    def test_add_ambiance(self):
        """
        Test case for add_ambiance

        Adds a new Ambiance.
        """
        pass

    def test_delete_ambiance(self):
        """
        Test case for delete_ambiance

        Removes a Ambiance from the database.
        """
        pass

    def test_get_ambiance(self):
        """
        Test case for get_ambiance

        Gets information ambiance from its id
        """
        pass

    def test_get_ambiances(self):
        """
        Test case for get_ambiances

        Gets all the ambiances information
        """
        pass

    def test_modify_ambiance(self):
        """
        Test case for modify_ambiance

        Modifies an existing Ambiance.
        """
        pass


if __name__ == '__main__':
    unittest.main()
